parameters:
    secret: symfony-test
    locale: en
    _locale: [fr,en]
         
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
                 
framework:
    form:            ~
    csrf_protection: ~
    session:
        handler_id:  session.handler.native_file
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    test: ~
    profiler:
        collect: false
    
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     127.0.0.1
        port:     null
        dbname:   symfony
        user:     root
        password: null
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true 