Cms\ContentBundle\Entity\Translation:
    properties:
        value:
           - NotBlank: ~
           
Cms\ContentBundle\Entity\TranslationRich:
    properties:
        value:
           - NotBlank: ~
    
             
               
           

    
     