parameters:
    
services:
    _defaults:
        autowire: true   
        autoconfigure: true 

    SYJS\JsBundle\:
        resource: '../src/'

    SYJS\JsBundle\Command\ExportFormCommand:
        arguments:
            $languages: '%SYJSJ.languages%'

    SYJS\JsBundle\Command\ExportEntityCommand:
        arguments:
            $languages: '%SYJSJ.languages%'
