Tools\AngularBundle\Entity\UserTest:
    properties:
        username:
             - NotBlank: ~
             - Regex:
                pattern: "/^[a-z0-9._-]+@[a-z0-9._-]{2,}\.[a-zA-Z]{2,4}/"
                match:   true
                message: test.regex
        password:
             - NotBlank: ~
             - Regex:
                pattern: "/[0-9]+/"
                match:   true
                message: test.regex
             - Regex:
                pattern: "/[a-zA-Z]+/"
                match:   true
                message: test.regex
             - Length:
                min: 2
                max: 5
                minMessage: test.min

 